name: realtime_chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  socket_io_client: ^2.0.3+1

  #Localization
  easy_localization: ^3.0.3

  #UI
  cupertino_icons: ^1.0.2

  #State
  flutter_bloc: ^8.1.3

  #Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  google_fonts: ^6.1.0

  #Navigation
  auto_route: ^7.8.4

  gen:
    path: module/gen/
  widgets:
    path: module/widgets/
dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  device_preview: ^1.1.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/translations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
